#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "This script should only be run as root"
    exit 1
fi

function logo {
		echo "$(tput setaf 2)
   .~~.   .~~.
  '. \ ' ' / .'$(tput setaf 1)
   .~ .~~~..~.
  : .~.'~'.~. :
 ~ (   ) (   ) ~
( : '~'.~.'~' : )
 ~ .~ (   ) ~. ~
  (  : '~' :  ) $(tput sgr0)Raspberry Pi$(tput setaf 1)
   '~ .~~~. ~'
       '~'
$(tput sgr0)"
sleep 2s
}
logo
while getopts "ufrsgch" opt; do
  case "$opt" in
	u)
		sudo pacman -Syu
	;;
	r)
		sudo shutdown -r now
	;;
	s)
		sudo shutdown -h now
	;;
	g)
		exit #sudo startx
	;;
	c)
		cd /mnt/HDD/youtube && ./convert.sh
	;;
	h)
		echo "[OPTIONS]"
		echo "-u	update"
		echo "-r	reboot"
		echo "-s	shutdown"
		echo "-g	start gui"
		echo "-c	convert youtube to mp3"
		exit
	;;
  esac
done
