#!/bin/bash

echo "$(tput setaf 2)
   .~~.   .~~.
  '. \ ' ' / .'$(tput setaf 1)
   .~ .~~~..~.
  : .~.'~'.~. :
 ~ (   ) (   ) ~
( : '~'.~.'~' : )
 ~ .~ (   ) ~. ~
  (  : '~' :  ) $(tput sgr0)Raspberry Pi$(tput setaf 1)
   '~ .~~~. ~'
       '~'
$(tput sgr0)"

if [[ $EUID -ne 0 ]]; then
    echo "This script should only be run as root"
    exit 1
fi

echo "what do you want to do:"
echo "update		[1]"
echo "reboot		[2]"
echo "shutdown 	[3]"
echo "start gui	[4]"
echo "convert		[5]"
echo "exit		[6]"
echo "What do you want to do now give number followd by [ENTER]:"
read option

case $option in
1)
sudo apt-get update && sudo apt-get dist-upgrade -y && sudo rpi-update && sudo shutdown -r now
;;
2)
sudo shutdown -r now
;;
3)
sudo shutdown -h now
;;
4)
sudo startx
;;
5)
cd /media/HDD/youtube && ./convert.sh
;;
6)
exit
;;
esac
